version: '3.8'

services:
  colorization-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  tensorboard:
    build: .
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/app/logs
    command: tensorboard --logdir=/app/logs --host=0.0.0.0 --port=6006
    restart: unless-stopped
